language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
jobs:
  include:
    - stage: release
      node_js: 8
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release